spring:
  config:
    activate:
      on-profile:
        active: local

---
spring:
  profile: local



  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update # 기존 create-drop에서 update로 수정

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE # 데이터베이스 종료 방지 설정 추가
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true # H2 콘솔 활성화
      path: /h2-console # 콘솔 경로 설정

  main:
    allow-circular-references: true
